version: '3.8'
services:

  web:
    container_name: oe-web
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
     - db
    ports:
     - 8000:8000
    environment:
      APP_NAME: 'Open Ecommerce'
      APP_KEY: base64:dUU/tjDaLvZv2ChevcXI87IBIoIK9DA4o/UGt5aAa3E=
    working_dir: /app
    volumes:
      - ./:/app
  db:
    container_name: oe-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: open_ecommerce
  
  adminer:
    container_name: oe-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080