name: Unit and Feature tests via PHPUnit by Dependabot

on:
  pull_request:
    branches: master

jobs:
  laravel-tests:
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: open_ecommerce
        ports:
          - 3306:3306
    if: github.actor == 'dependabot[bot]'
    environment: open_ecommerce
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Copy .env
      run: |
        php -r "copy('.env.test', '.env');"
        sed -i "s/RAJAONGKIR_API_KEY=.*/RAJAONGKIR_API_KEY=${{ secrets.RAJAONGKIR_API_KEY }}/g" .env
        cat .env
    - name: Install and update Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Clear cache
      run: php artisan config:cache
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: DB Migration
      run: php artisan migrate
    - name: DB Seed
      run: php artisan db:seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
