name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup RAJAONGKIR API KEY
      run: |
        sed -i "s/RAJAONGKIR_API_KEY=.*/RAJAONGKIR_API_KEY=/g" .env.docker
        sed -i 's/RAJAONGKIR_API_KEY=.*/RAJAONGKIR_API_KEY=${{ secrets.RAJAONGKIR_API_KEY }}/g' .env.docker
        cat .env.docker
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s
    - name: update config
      run: |
        docker exec oe-web php artisan config:clear
        docker exec oe-web php artisan config:cache
    - name: database migration
      run: docker exec oe-web php artisan migrate
    - name: database seed
      run: docker exec oe-web php artisan db:seed
    - name: run test
      run: docker exec oe-web php artisan test