name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: change env
      run: |
        cp .env.docker .env
        sed -i "s/RAJAONGKIR_API_KEY=.*/RAJAONGKIR_API_KEY=${{ secrets.RAJAONGKIR_API_KEY }}/g" .env
        cat .env
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s
    - name: database migration with docker
      run: docker exec oe-web php artisan migrate
    - name: database seed with docker
      run: docker exec oe-web php artisan db:seed
